name: Quality & Build Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  quality-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Run code quality checks (format, lint, type-check)
        run: npm run validate

      - name: Build project
        run: npm run build

      - name: Verify build artifacts
        run: |
          if [ ! -f "dist/index.js" ]; then
            echo "❌ Build artifact dist/index.js not found"
            exit 1
          fi
          echo "✅ Build artifact dist/index.js verified"

      - name: Check build artifact size
        run: |
          if [ -f "dist/index.js" ]; then
            SIZE=$(stat -c%s "dist/index.js")
            echo "📦 Build artifact size: ${SIZE} bytes"
            if [ $SIZE -lt 1000 ]; then
              echo "⚠️  Warning: Build artifact seems unusually small"
            fi
          fi
